name: Fork Sync

on:
  schedule:
    - cron: '0 * * * *'  # 每一小时自动同步一次
  workflow_dispatch:       # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Fork Sync
        uses: tgymnich/fork-sync@v1.2.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          head: main        # 上游源仓库的分支
          base: main        # 你 fork 仓库中要保持更新的分支
          merge_method: merge
